# Generated by Django 5.2.8 on 2025-12-06 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('presidente', 'PRESIDENTE'), ('secretaria', 'SECRETARIA'), ('tesorero', 'TESORERO'), ('suplente', 'SUPLENTE'), ('vecino', 'VECINO')], max_length=20)),
                ('rut', models.CharField(help_text='12345678-9', max_length=12, unique=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('recovery_code', models.CharField(blank=True, max_length=6, null=True)),
                ('recovery_code_expires', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.CharField(default='', max_length=255, verbose_name='Nombre de la Calle/Pasaje')),
                ('numero_casa', models.CharField(blank=True, default='', max_length=20, verbose_name='N° Casa/Depto/Lote')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('total_residentes', models.PositiveIntegerField(default=1, verbose_name='Total de Residentes')),
                ('total_ninos', models.PositiveIntegerField(default=0, verbose_name='Número de Niños (< 18 años)')),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token FCM')),
                ('debe_cambiar_password', models.BooleanField(default=False, verbose_name='Debe cambiar contraseña')),
                ('mfa_code', models.CharField(blank=True, max_length=6, null=True)),
                ('mfa_expires', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rut', ''), _negated=True), name='rut_not_empty')],
            },
        ),
    ]
