# Generated by Django 5.2.8 on 2025-12-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_id_oltp', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_reunion', models.DateField()),
                ('precision_transcripcion', models.FloatField(default=0.0, help_text='Porcentaje 0-100')),
            ],
        ),
        migrations.CreateModel(
            name='DimReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reunion_id_oltp', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DimTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taller_id_oltp', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('cupos_totales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DimVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vecino_id_oltp', models.IntegerField(help_text='ID original del modelo User', unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rango_etario', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('tiene_niños', models.BooleanField(default=False)),
                ('usa_app_movil', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DimVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion_id_oltp', models.IntegerField(unique=True)),
                ('pregunta', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FactCalidadTranscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_palabras', models.IntegerField()),
                ('palabras_correctas', models.IntegerField()),
                ('precision_porcentaje', models.FloatField()),
                ('origen', models.CharField(default='SIMULADO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FactMetricasDiarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tiempo_respuesta_ms', models.IntegerField(help_text='Promedio en ms')),
                ('disponibilidad_sistema', models.FloatField(help_text='Porcentaje 0-100')),
                ('fallos_votacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FactMetricasTecnicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tiempo_respuesta_ms', models.IntegerField()),
                ('disponibilidad', models.FloatField()),
                ('fallos_votacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FactAsistenciaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimreunion')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimvecino')),
            ],
        ),
        migrations.CreateModel(
            name='FactConsultaActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimacta')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimvecino')),
            ],
        ),
        migrations.CreateModel(
            name='FactInscripcionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField()),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimtaller')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimvecino')),
            ],
        ),
        migrations.CreateModel(
            name='FactParticipacionVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField()),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimvecino')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamart.dimvotacion')),
            ],
        ),
    ]
