# Generated by Django 5.2.8 on 2025-12-06 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('Ordinaria', 'Ordinaria'), ('Extraordinaria', 'Extraordinaria')], default='Ordinaria', max_length=20)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tabla', models.TextField(verbose_name='Tabla de contenidos')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='acta', serialize=False, to='reuniones.reunion')),
                ('contenido', models.TextField(blank=True, default='Borrador del acta...')),
                ('aprobada', models.BooleanField(default=False)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('archivo_audio', models.FileField(blank=True, help_text='Archivo de audio (.webm, .ogg) subido por la directiva.', null=True, upload_to='audios_reuniones/')),
                ('estado_transcripcion', models.CharField(choices=[('NO_SUBIDO', 'No Subido'), ('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='NO_SUBIDO', max_length=20)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_aprobadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogConsultaActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_de_actas', to=settings.AUTH_USER_MODEL)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='reuniones.acta')),
            ],
            options={
                'verbose_name': 'Log de Consulta de Acta',
                'verbose_name_plural': 'Logs de Consultas de Actas',
            },
        ),
        migrations.CreateModel(
            name='ActaEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_enviados', to='reuniones.acta')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='reuniones.reunion')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reunion', 'vecino')},
            },
        ),
    ]
