# Generated by Django 5.2.8 on 2025-12-06 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Recurso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=True, help_text='Marcar si el recurso está disponible para ser reservado.')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio de la reserva')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin de la reserva')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por Vecino')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(verbose_name='Motivo de la reserva')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='recursos.recurso')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_hechas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por Vecino')], db_index=True, default='PENDIENTE', max_length=10)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='recursos.recurso')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_el'],
                'indexes': [models.Index(fields=['recurso', 'fecha_inicio', 'fecha_fin'], name='recursos_so_recurso_08ecaf_idx'), models.Index(fields=['estado'], name='recursos_so_estado_929cf6_idx'), models.Index(fields=['solicitante', 'recurso'], name='recursos_so_solicit_4d45df_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='solicitud_fin_gte_inicio'), models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('solicitante', 'recurso'), name='uniq_pendiente_por_usuario_y_recurso')],
            },
        ),
    ]
